### ISSUE TITLE
pretrained_model

### ISSUE THREAD

**Issue by pradeepkc11** [noorchauhan/DeepFake-Audio-Detection-MFCC#2]
can you please provide the pretrained model for Deepfake audio detection so that i can use to my audio files and my mail id is pradeep.kcsmg@gmail.com

**Comment by noorchauhan** [comment]
Hey Pradeep, our model was trained with not more than 3 samples, it is not accurate. follow the [README.md](https://github.com/noorchauhan/DeepFake-Audio-Detection-MFCC/blob/main/README.md) to make your own
