### ISSUE TITLE
files missing

### ISSUE THREAD

**Issue by pradeepkc11** [noorchauhan/DeepFake-Audio-Detection-MFCC#3]
I am not able to find the analyze_audio.py file in the repository where is that file

**Comment by noorchauhan** [comment]
1. Run the main.py file then run the app.py file after you have checked for all prerequisites 
2. Open the localhost where the python server is running.

Our analyze_audio.py file was used to demonstrate the working of the project from the terminal to the judges, the GUI was just a cherry on top, you can simply code the same audio_ananlyze.py by yourself.

`Import packages
call for all required audio files
classify as real and fake
RUN the main.py
& there you have it`
